// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import {ConvexClientProviders} from "@/providers/ConvexClientProviders";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }; 

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <ConvexClientProviders>
//           {children}
//         </ConvexClientProviders>
//       </body>
//     </html>
//   );
// }




import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ConvexClientProviders} from "@/providers/ConvexClientProviders";
import { TooltipProvider } from "@radix-ui/react-tooltip";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProviders>
          <TooltipProvider>

          {children}
          </TooltipProvider>
        </ConvexClientProviders>
      </body>
    </html>
  );
}
